name: journal_it_top
description: Мобильное приложение электронного дневника для колледжа.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/logo.png'
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
